<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CitiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('cities')->insert([
            ['city_name' => 'Casablanca'],
            ['city_name' => 'Rabat'],
            ['city_name' => 'Fes'],
            ['city_name' => 'Marrakech'],
            ['city_name' => 'Tangier'],
            ['city_name' => 'Agadir'],
            ['city_name' => 'Meknes'],
            ['city_name' => 'Oujda'],
            ['city_name' => 'Kenitra'],
            ['city_name' => 'Temara'],
            ['city_name' => 'Safi'],
            ['city_name' => 'Mohammedia'],
            ['city_name' => 'El Jadida'],
            ['city_name' => 'Khouribga'],
            ['city_name' => 'Beni Mellal'],
            ['city_name' => 'Nador'],
            ['city_name' => 'Settat'],
            ['city_name' => 'Berrechid'],
            ['city_name' => 'Khenifra'],
            ['city_name' => 'Fquih Ben Salah'],
            ['city_name' => 'Dakhla'],
            ['city_name' => 'Tan-Tan'],
            ['city_name' => 'Skhirat'],
            ['city_name' => 'Oued Zem'],
            ['city_name' => 'Youssoufia'],
            ['city_name' => 'Larache'],
            ['city_name' => 'Ksar El Kebir'],
            ['city_name' => 'Chefchaouen'],
            ['city_name' => 'Errachidia'],
            ['city_name' => 'Guercif'],
            ['city_name' => 'Tarfaya'],
            ['city_name' => 'Moulay Yacoub'],
            ['city_name' => 'Sidi Kacem'],
            ['city_name' => 'Oulad Teima'],
            ['city_name' => 'Ben Guerir'],
            ['city_name' => 'Tinghir'],
            ['city_name' => 'Assa'],
            ['city_name' => 'Sefrou'],
            ['city_name' => 'Ouarzazate'],
            ['city_name' => 'Souk Larbaa'],
            ['city_name' => 'Lqliaa'],
            ['city_name' => 'Asilah'],
            ['city_name' => 'Khemisset'],
            ['city_name' => 'Ifrane'],
            ['city_name' => 'Tata'],
            ['city_name' => 'Sidi Yahia El Gharb'],
            ['city_name' => 'Oued Laou'],
            ['city_name' => 'Bouznika'],
            ['city_name' => 'Tahala'],
            ['city_name' => 'Imzouren'],
            ['city_name' => 'Ain Harrouda'],
            ['city_name' => 'Azemmour'],
            ['city_name' => 'Al Hoceima'],
            ['city_name' => 'Guelmim'],
            ['city_name' => 'Skhirate'],
            ['city_name' => 'Benslimane'],
            ['city_name' => 'Dcheira El Jihadia'],
            ['city_name' => 'Martil'],
            ['city_name' => 'Fnideq'],
            ['city_name' => 'Sidi Smail'],
            ['city_name' => 'Berkane'],
            ['city_name' => 'Khemis Zemamra'],
            ['city_name' => 'Sidi Rahal'],
            ['city_name' => 'Sidi Allal El Bahraoui'],
            ['city_name' => 'Boujdour'],
            ['city_name' => 'Dar Bouazza'],
            ['city_name' => 'Figuig'],
            ['city_name' => 'Zagora'],
            ['city_name' => 'Skoura'],
            ['city_name' => 'Ouezzane'],
            ['city_name' => 'Oulad Tayma'],
            ['city_name' => 'Bir Gandouz'],
            ['city_name' => 'Bhalil'],
            ['city_name' => 'Oued Amlil'],
            ['city_name' => 'Sidi Bou Othmane'],
            ['city_name' => 'Taounate'],
            ['city_name' => 'Sidi Bennour'],
            ['city_name' => 'Talmest'],
            ['city_name' => 'Lakhnifri'],
            ['city_name' => 'Sidi Ifni'],
            ['city_name' => 'Smara'],
            ['city_name' => 'Tafraout'],
            ['city_name' => 'Boumalne Dadès'],
            ['city_name' => 'Drargua'],
            ['city_name' => 'El Aioun'],
            ['city_name' => 'El Guerdane'],
            ['city_name' => 'El Hajeb'],
            ['city_name' => 'Goulmima'],
            ['city_name' => 'Lakhsas'],
            ['city_name' => 'Sidi Taibi'],
            ['city_name' => 'Tidjikja'],
            ['city_name' => 'Zaio'],
            ['city_name' => 'Afourar'],
            ['city_name' => 'Bouanane'],
            ['city_name' => 'Imouzzer Kandar'],
            ['city_name' => 'Jerada'],
            ['city_name' => 'Laattaouia'],
            ['city_name' => 'Midelt'],
            ['city_name' => 'Missour'],
            ['city_name' => 'Moulay Abdallah'],
            ['city_name' => 'Ouazzane'],
            ['city_name' => 'Oulad Ayad'],
            ['city_name' => 'Oulad Berhil'],
            ['city_name' => 'Oulad Frej'],
            ['city_name' => 'Oulad Ghadbane'],
            ['city_name' => 'Oulad H Riz Sahel'],
            ['city_name' => 'Oulad M Barek'],
            ['city_name' => 'Oulad M Rah'],
            ['city_name' => 'Oulad Zbair'],
            ['city_name' => 'Ouled Tayeb'],
            ['city_name' => 'Ounagha'],
            ['city_name' => 'Sidi Allal Tazi'],
            ['city_name' => 'Sidi Bouknadel'],
            ['city_name' => 'Sidi Bouzid'],
            ['city_name' => 'Sidi Bouzineb'],
            ['city_name' => 'Sidi Harazem'],
            ['city_name' => 'Sidi Lamine'],
            ['city_name' => 'Sidi Lyamani'],
            ['city_name' => 'Sidi Moussa'],
            ['city_name' => 'Sidi Redouane'],
            ['city_name' => 'Sidi Slimane'],
            ['city_name' => 'Tahannaout'],
            ['city_name' => 'Tahar Souk'],
        ]);
    }
}

